name: CI/CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Workflow-level environment variables
env:
  APP_NAME: "URL Shortener App"
  GLOBAL_DEBUG: false
  PYTHON_VERSION: "3.10"

jobs:
  build-selfhosted-windows:
    runs-on: [self-hosted, Windows]
 
      
    # Job-level environment Variables
    env:
      GLOBAL_DEBUG: true
      BUILD_STAGE: "Build Job"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Debug DATABASE_URL
        run: echo DATABASE_URL=${{ env.DATABASE_URL }}
        shell: cmd

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello from Windows self-hosted runner!"

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Start PostgreSQL with Docker
        shell: cmd
        run: |
          docker rm -f my_postgres || echo "Container not found"
          docker run -d --name my_postgres ^
          -p 5432:5432 ^
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} ^
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} ^
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} ^
          postgres:15
          
      - name: Check Postgres logs
        run: docker logs my_postgres
        shell: cmd

      - name: Wait for Postgres to be ready
        shell: powershell
        run: |
          Write-Host "Waiting for Postgres..."
          Start-Sleep -Seconds 20

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          sleep 10  # Ensure DB container is ready

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    
      - name: Run unit tests with coverage
        run: |
          pip install pytest pytest-cov
          $Env:PYTHONPATH = "."
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Print variable scopes
        env:
          BUILD_STAGE: "Step Override"
          STEP_ONLY: "This only exists here"
        run: |
          echo "Workflow APP_NAME: $APP_NAME"
          echo "Job-level GLOBAL_DEBUG: $GLOBAL_DEBUG"
          echo "Job-level BUILD_STAGE: $BUILD_STAGE"
          echo "Step-level STEP_ONLY: $STEP_ONLY"
      
  deploy:
   needs: build-selfhosted-windows
   runs-on: [self-hosted, Windows]

   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ghcr.io/archi1912/url-shortener:latest .

    - name: List local Docker images
      run: docker images

    #  Use PAT for login instead of GITHUB_TOKEN
    - name: Docker logout
      run: docker logout ghcr.io
      shell: powershell

    - name: Docker login to GHCR with PAT
      shell: powershell
      env:
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
      run: docker login ghcr.io -u archi1912 -p $Env:GHCR_PAT     
      
    - name: Push Docker image
      run: docker push ghcr.io/archi1912/url-shortener:latest

    - name: Remove previous container if exists
      shell: powershell
      run: |
        $container = docker ps -a -q -f name=***
        if ($container) {
          docker rm -f ***
        } else {
          Write-Host "No previous container"
        }

    - name: Pull image from GitHub Packages
      run: docker pull ghcr.io/archi1912/url-shortener:latest

    - name: Remove previous container if exists
      shell: powershell
      run: |
        if (docker ps -a -q -f name=url_shortener) {
          docker rm -f url_shortener
          echo "Removed existing url_shortener container"
        } else {
          echo "No previous container to remove"
        }

    - name: Run container locally
      run: docker run -d --name url-shortenerr  -p 8000:8000 -e DATABASE_URL="${{ secrets.DATABASE_URL_DEPLOY }}" ghcr.io/archi1912/url-shortener:latest

    - name: Wait for container startup
      run: sleep 10

    - name: List running containers
      run: docker ps

    - name: Install Docker Compose plugin on Windows
      shell: powershell
      run: |
        $pluginDir = "$Env:USERPROFILE\.docker\cli-plugins"
        New-Item -ItemType Directory -Force -Path $pluginDir | Out-Null
        $pluginPath = Join-Path $pluginDir "docker-compose.exe"
        Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-windows-x86_64.exe" -OutFile $pluginPath
    
    - name: Start Docker Compose
      run: docker compose up -d

    - name: Wait for Postgres to be ready
      shell: powershell
      run: |
        for ($i=1; $i -le 30; $i++) {
          docker compose exec db pg_isready -U postgres
          if ($LASTEXITCODE -eq 0) {
            Write-Host "Postgres is ready!"
            break
          } else {
            Write-Host "Waiting for Postgres..."
            Start-Sleep -Seconds 2
          }
        }

    - name: Wait for app to be ready
      shell: powershell
      run: |
        for ($i=1; $i -le 15; $i++) {
          try {
            Invoke-WebRequest -Uri http://localhost:8000 -UseBasicParsing
            Write-Host "App is ready!"
            break
          } catch {
            Write-Host "Waiting for app..."
            Start-Sleep -Seconds 2
          }
        }
    - name: Show running containers
      shell: powershell
      run: docker ps -a

    - name: Show app container logs
      shell: powershell
      run: docker logs url-shortenerr
  
    - name: Wait for app to start with retry
      shell: powershell
      run: |
        $success = $false
        for ($i=1; $i -le 10; $i++) {
          try {
            Invoke-WebRequest -Uri "http://localhost:8000" -UseBasicParsing -TimeoutSec 5
            Write-Host "App started"
            $success = $true
            break
          } catch {
            Write-Host "Waiting for app..."
            Start-Sleep -Seconds 3
          }
        }
        if (-not $success) {
          Write-Host "App failed to start in time"
          exit 1
        }
